### ISSUE TITLE
Datasource class could not be found.

### ISSUE THREAD

**Issue by behrus** [sters/cakephp3-aws-s3-datasource#1]
Hi there,

i flowed your construction to install and use your aws plugin for cke3.

But when i call controller action, i got errors from cake like below:

**Datasource class my_s3_connection could not be found.**

Another question about adding datasource in app,php

I have block 'Datasources' in my app for database connection. There should then be adding the datasource of your plugin?
I did it in my app like below:
` 
 'Datasources' => [
        'default' => [
            'className' => 'Cake\Database\Connection',
            'driver' => 'Cake\Database\Driver\Mysql',
            'persistent' => false,
            -----
        ],
        'my_s3_connection' => [
            'class'      => 'CakeS3\Datasource\Connection',
            'key'        => 'kjhgjkgkjh',
            'secret'     => 'gjkgkjgh',
            'bucketName' => 'jmkkjhjkjh'
        ],
    ],
`

Thank in advance

**Comment by sters** [comment]
Thanks reporting!

I'll check it, wait a moment.

**Comment by sters** [comment]
Maybe, readme.md wrong. I'm sorry.

I fixed wrong place, how about this?

```
'Datasource' => [
    'my_s3_connection' => [
        // wrong configure
        // 'class' => 'CakeS3\Datasource\Connection',

        // maybe
        'className'  => 'CakeS3\Datasource\Connection',
        'key'        => 'put your s3 access key',
        'secret'     => 'put your s3 access secret',
        'bucketName' => 'put your bucket name',
    ],
],
```

If you success AWS S3 connection, I fix README.md.

**Comment by sters** [comment]
@behrus I'm fix README.md file. check it > https://github.com/sters/cakephp3-aws-s3-datasource/commit/9352e1f993d55233751a5b503f0ed9b01005ed6a
