### ISSUE TITLE
I have message Bucket not found

### ISSUE THREAD

**Issue by felipesudrj** [sters/cakephp3-aws-s3-datasource#2]
I have a message, Bucket 'MyBucketName' is not found.
But my name bucket is correct.
What can it be?

**Comment by sters** [comment]
umm, I don't know that trouble.
I will debug in the next few hours.

**Comment by sters** [comment]
OK, I found some bugs.

1. README mistake: add region configure, namespace typo.
2. Bucket exist check: I write throw away that AWS SDK's S3 client throws some error.
    + Configure token does not have bucket access auth.
    + Something curl error.
3. Not compatible CakePHP 3.6+
    + `logger` method is deprecated. rename to `getLogger/setLogger`.

I fixed that bugs and published packagist.

Try new version of 0.0.3.

+ `composer install` after remove `composer.lock`
+ or `composer update`

----

FYI:

My computer's (windows10) PHP enviroment had curl error in section 2.

```
AWS HTTP error: cURL error 60: SSL certificate problem: unable to get local issuer certificate (see http://curl.haxx.se/libcurl/c/libcurl-errors.html)
```

I don't saw error after changed curl section's ca certs configure in php.ini.

```
[curl]
curl.cainfo = "C:\Program Files\Git\etc\pki\ca-trust\extracted\openssl\ca-bundle.trust.crt"
```
(My computer installed git-for-windows.)

**Comment by felipesudrj** [comment]
tks brow!
